dbt_cloud_oct:
  outputs:
    dev:
      account: FCB96082
      database: analytics
      password: Sachin$123
      role: analyticsengineer
      schema: dbt_tjain
      threads: 3
      type: snowflake
      user: sachin
      warehouse: transform_wh
  target: dev

