sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers

      - name: partsupps 
      - name: nations
      - name: regions

      - name: suppliers
      - name: orders
        config:
          freshness:
            warn_after: {count: 3, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: o_orderdate::timestamp_ntz
      - name: lineitems
      - name: parts

  - name: stg_src
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees