sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: v_nations
      - name : stg_nations
      - name : nations
      - name : suppliers
      - name : regions

      - name: orders
        config:
          freshness:
            warn_after: {count: 1, period: hour}
            error_after: {count: 1, period: hour}
          loaded_at_field: o_orderdate::timestamp_ntz
      - name: lineitems
      - name: parts

  - name: stg_src
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees